development:
  adapter: postgresql
  database: notella_dev
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  
production: 
  adapter: postgresql
  database: postgres
  encoding: utf8
  pool: 5
  timeout: 5000
